ALR-194
bcgov/MOH-ALR pull request #561
Opened 2024-03-20 16:06 UTC by gorishAccn

create CAT Assessment report

2024-03-20 16:16 UTC, Sumancdey approved these changes

2024-03-21 13:55 UTC, GandlojuVishwantha requested changes
Remove .gitignore file from the branch

2024-03-22 07:20 UTC, GandlojuVishwantha requested changes
@gorishAccn Could you please remove .gitignore file any reason you are adding this file

2024-03-22 07:34 UTC, Sumancdey approved these changes

2024-03-22 13:40 UTC, GandlojuVishwantha approved these changes

2024-03-22 15:28 UTC, Sumancdey approved these changes

2024-03-22 16:36 UTC, merged